[build]
  command = "npm run build && cp ./index.html ./dist"
  functions = "dist"
  publish = "dist"

[context.production.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs10.x"

[template.environment]
  ASSISTANT_KEY = "Assistant key from playpirates.com site"
  
